/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, createHandlerBoundToURL, cleanupOutdatedCaches } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare let self: ServiceWorkerGlobalScope

clientsClaim()
self.skipWaiting()

// Ensure old caches from previous PWA versions are wiped
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Fallback for SPA navigation
try {
    // Vite PWA might cache index.html as 'index.html' or '/index.html' depending on the platform/config.
    // We try both to ensure the navigation route is successfully registered.
    let handler;
    try {
        handler = createHandlerBoundToURL('index.html')
    } catch {
        handler = createHandlerBoundToURL('/index.html')
    }
    const navigationRoute = new NavigationRoute(handler)
    registerRoute(navigationRoute)
} catch (error) {
    console.error("Error setting up navigation fallback", error)
}
